spring:
  config:
    import:
      - monitoring.yml
      - logback.yml
      - rdbms-application.yml
      - nosql-application.yml
      - client-application.yml
  web.resources.add-mappings: false

server:
  port: 8080
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

