spring:
  datasource:
    url: jdbc:mariadb://???:3306/???
    username: root
    password: 6548
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
