spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DB_CUSTOM_INDEX_STRATEGY
    username: root
    password: 6548

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
