version: '3.7'
services:
  springboot-app:
    container_name: springboot-container-blue
    build:
      context: .
      dockerfile: springboot-dockerfile
    image: springboot-app:blue
    ports:
      - "8081:8080"