spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch-test
    username: root
    password: 6548
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create

  batch:
    initialize-schema: always