spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch-test
    username: root
    password: 6548
    driver-class-name: org.mariadb.jdbc.Driver
    schema: classpath:schema-mariadb.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  batch:
    initialize-schema: always
    job:
      enabled: true
